apiVersion: apps/v1
kind: Deployment
metadata:
  name: waow-official
  namespace: default
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: waow-official-container
          resources:
            requests:
              cpu: 150m
              memory: 256Mi
            limits:
              cpu: 350m
              memory: 512Mi
