apiVersion: apps/v1
kind: Deployment
metadata:
  name: waow-official
  namespace: default
  labels:
    app: waow-official
spec:
  replicas: 1
  selector:
    matchLabels:
      app: waow-official
  template:
    metadata:
      labels:
        app: waow-official
    spec:
      tolerations:
        - key: instance_type
          value: whitelabel
          effect: NoSchedule
          operator: Equal
      containers:
        - name: waow-official-container
          image: LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE:TAG
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: 150m
              memory: 256Mi
            limits:
              cpu: 350m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
            timeoutSeconds: 3
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
